export const SET_FIRST_NAME = 'SET_FIRST_NAME';

export const SET_LAST_NAME = 'SET_LAST_NAME';

export const SET_EMAIL = 'SET_EMAIL';

export const SET_POLICY_NO = 'SET_POLICY_NO';

export const SET_DATE_OF_BIRTH = 'SET_DATE_OF_BIRTH';

export const SET_DESCRIPTION = 'SET_DESCRIPTION';

export const SET_STAGE = 'SET_STAGE';

export const SET_IS_FORM_VALID = 'SET_IS_FORM_VALID';

export const CLEAR_FORM = 'CLEAR_FORM';

export const SET_FORM_MESSAGE = 'SET_FORM_MESSAGE';


export const SET_FIRST_NAME_STATE = 'SET_FIRST_NAME_STATE';

export const SET_LAST_NAME_STATE = 'SET_LAST_NAME_STATE';

export const SET_EMAIL_STATE = 'SET_EMAIL_STATE';

export const SET_POLICY_NO_STATE = 'SET_POLICY_NO_STATE';

export const SET_DATE_OF_BIRTH_STATE = 'SET_DATE_OF_BIRTH_STATE';
